#baseurl = "/"
baseurl = "https://manjaro.github.io/homepage/public/"
languageCode = "en-us"
title = "Manjaro Linux - enjoy the simplicity"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
        # information about you and your website.
	name = "Manjaro Linux"
	description = "Linux Distribution"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Manjaro"

		[params.navigation.links]
			about     = "About"
			services  = "Features"
			portfolio = "Get"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		image = "manjaro-logo.png	"
		slogan     = "MANJARO<br />Linux fast and stable."
		subtitle   = "The easy to install Linux distribution with a friendly feel that comes with the latest and greatest apps at your fingertips."
		buttonText = "Learn more"
		callToAction = "Download Manjaro"
		callToActionUrl = "//manjaro.github.io/download"
		otherDownloads = "See all versions."
		otherDownloadsurl= "//manjaro.github.io/download"



	# About section
	[params.about]
		headline    = "Grows with you."
		description = "Built a powerful Arch-Linux foundation, with speed, efficiency and cutting edge software, Manjaro makes it stable and takes full advantage of your computer hardware. It is designed to make beginners happy and grow with them while they are becomming advanced users. It is easy to install even for beginners and comes with all the apps you need every day."
		buttonText  = "Get started!"

	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Rock Stable"
            description = "Our Linux Distribution is well tested and has several branches."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "You can use this Linux Distribution as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "We update our packages to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "You have to make your Linux Distribution with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get Manjaro Linux"

		[params.aside.button]
			text = "Download now"
			link = "//manjaro.github.io/download"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Checkout our github project or send us an email and we will get back to you as soon as possible!"
		github = "manjaro"
		email = "support@manjaro.org"
